

server:
  port: 8080


spring:
  security:
    user:
      name: postgres
      password: silasila
  messages:
    basename: messages
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/project_db
    username: postgres
    password: silasila
    driverClassName: org.postgresql.Driver
    initialization-mode: always

logging:
  level:
    com:
      hibernate: DEBUG